# Generated by Django 4.2.11 on 2024-04-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bookings', '0002_alter_booking_num_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='extras',
            name='price',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='price',
        ),
    ]
