# Generated by Django 4.2.11 on 2024-04-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_bookings', '0005_alter_review_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
